"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-06-22 05:11:15.149824

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), server_default=sa.text("'operator'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admins')),
    sa.UniqueConstraint('email', name=op.f('uq_admins_email'))
    )
    op.create_table('products',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('points_value', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('points_value >= 0', name=op.f('ck_products_points_value_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_table('users',
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('phone', name=op.f('uq_users_phone'))
    )
    op.create_table('audit_logs',
    sa.Column('actor_admin_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_admin_id'], ['admins.id'], name=op.f('fk_audit_logs_actor_admin_id_admins')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_table('qr_batches',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admins.id'], name=op.f('fk_qr_batches_created_by_admin_id_admins')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_qr_batches_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qr_batches'))
    )
    op.create_table('redemption_requests',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('processed_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('points > 0', name=op.f('ck_redemption_requests_points_positive')),
    sa.ForeignKeyConstraint(['processed_by_admin_id'], ['admins.id'], name=op.f('fk_redemption_requests_processed_by_admin_id_admins')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_redemption_requests_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_redemption_requests'))
    )
    op.create_index('ix_redemption_requests_status', 'redemption_requests', ['status'], unique=False)
    op.create_index('ix_redemption_requests_user_id_created_at', 'redemption_requests', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('product_units',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('claimed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('active','claimed','void')", name=op.f('ck_product_units_status_valid')),
    sa.ForeignKeyConstraint(['batch_id'], ['qr_batches.id'], name=op.f('fk_product_units_batch_id_qr_batches')),
    sa.ForeignKeyConstraint(['claimed_by_user_id'], ['users.id'], name=op.f('fk_product_units_claimed_by_user_id_users')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_units_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_units')),
    sa.UniqueConstraint('token', name=op.f('uq_product_units_token'))
    )
    op.create_index('ix_product_units_batch_id', 'product_units', ['batch_id'], unique=False)
    op.create_index('ix_product_units_product_id', 'product_units', ['product_id'], unique=False)
    op.create_index('ix_product_units_status', 'product_units', ['status'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('product_unit_id', sa.UUID(), nullable=True),
    sa.Column('redemption_id', sa.UUID(), nullable=True),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], name=op.f('fk_ledger_entries_admin_id_admins')),
    sa.ForeignKeyConstraint(['product_unit_id'], ['product_units.id'], name=op.f('fk_ledger_entries_product_unit_id_product_units')),
    sa.ForeignKeyConstraint(['redemption_id'], ['redemption_requests.id'], name=op.f('fk_ledger_entries_redemption_id_redemption_requests')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ledger_entries_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entries'))
    )
    op.create_index('ix_ledger_entries_type', 'ledger_entries', ['type'], unique=False)
    op.create_index('ix_ledger_entries_user_id_created_at', 'ledger_entries', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ledger_entries_user_id_created_at', table_name='ledger_entries')
    op.drop_index('ix_ledger_entries_type', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index('ix_product_units_status', table_name='product_units')
    op.drop_index('ix_product_units_product_id', table_name='product_units')
    op.drop_index('ix_product_units_batch_id', table_name='product_units')
    op.drop_table('product_units')
    op.drop_index('ix_redemption_requests_user_id_created_at', table_name='redemption_requests')
    op.drop_index('ix_redemption_requests_status', table_name='redemption_requests')
    op.drop_table('redemption_requests')
    op.drop_table('qr_batches')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('admins')
    # ### end Alembic commands ###
