"""dealer rewards

Adds the dealer side to the shared schema. Autogenerate produced the tables and
columns; everything below the AUTOGENERATE marker is hand-written, because the
guarantees this product cannot ship without are partial unique indexes and
triggers, and Alembic cannot infer either:

  * uq_warranties_live_serial            one live warranty per physical unit
  * uq_allocations_open_serial           a serial belongs to one dealer at a time
  * uq_dealer_ledger_registration_credit a warranty is paid for exactly once
  * uq_dealer_point_rates_current        one current rate PER PRODUCT
  * dealer_ledger/warranty_events triggers  reject UPDATE and DELETE outright

Worker-side tables are untouched apart from two additive changes: audit_logs
gains a richer actor model (existing rows default to actor_type='admin', which
is what they were), and products gains warranty_months.

Revision ID: 0008
Revises: 0007
Create Date: 2026-08-20 01:47:00.437912

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: str | None = '0007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=400), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('is_phone_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('phone', name=op.f('uq_customers_phone'))
    )
    op.create_index('ix_customers_name', 'customers', ['name'], unique=False)
    op.create_table('dealer_rewards',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('points_cost', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=600), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('points_cost > 0', name=op.f('ck_dealer_rewards_points_cost_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dealer_rewards'))
    )
    op.create_table('dealers',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=400), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('gst_number', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('active','suspended','closed')", name=op.f('ck_dealers_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dealers')),
    sa.UniqueConstraint('code', name=op.f('uq_dealers_code'))
    )
    op.create_index('ix_dealers_status', 'dealers', ['status'], unique=False)
    op.create_table('allocation_batches',
    sa.Column('filename', sa.String(length=400), nullable=True),
    sa.Column('uploaded_by_admin_id', sa.UUID(), nullable=False),
    sa.Column('row_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('ok_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('errors', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_admin_id'], ['admins.id'], name=op.f('fk_allocation_batches_uploaded_by_admin_id_admins')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_allocation_batches'))
    )
    op.create_table('dealer_point_rates',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('points_per_registration', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_to is null or effective_to >= effective_from', name=op.f('ck_dealer_point_rates_window_ordered')),
    sa.CheckConstraint('points_per_registration >= 0', name=op.f('ck_dealer_point_rates_points_non_negative')),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admins.id'], name=op.f('fk_dealer_point_rates_created_by_admin_id_admins')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_dealer_point_rates_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dealer_point_rates'))
    )
    op.create_index('ix_dealer_point_rates_product_id', 'dealer_point_rates', ['product_id'], unique=False)
    op.create_table('dealer_staff',
    sa.Column('dealer_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), server_default=sa.text("'staff'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role in ('owner','staff')", name=op.f('ck_dealer_staff_role_valid')),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], name=op.f('fk_dealer_staff_dealer_id_dealers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dealer_staff')),
    sa.UniqueConstraint('phone', name=op.f('uq_dealer_staff_phone'))
    )
    op.create_index('ix_dealer_staff_dealer_id', 'dealer_staff', ['dealer_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('dealer_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.String(length=120), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'in_progress'"), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('in_progress','completed')", name=op.f('ck_idempotency_keys_status_valid')),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], name=op.f('fk_idempotency_keys_dealer_id_dealers')),
    sa.PrimaryKeyConstraint('key', 'dealer_id', name=op.f('pk_idempotency_keys'))
    )
    op.create_index('ix_idempotency_keys_created_at', 'idempotency_keys', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('allocations',
    sa.Column('serial', sa.String(length=128), nullable=False),
    sa.Column('dealer_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'allocated'"), nullable=False),
    sa.Column('dispatch_ref', sa.String(length=120), nullable=True),
    sa.Column('allocated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('allocated','registered','revoked','returned')", name=op.f('ck_allocations_status_valid')),
    sa.ForeignKeyConstraint(['batch_id'], ['allocation_batches.id'], name=op.f('fk_allocations_batch_id_allocation_batches')),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], name=op.f('fk_allocations_dealer_id_dealers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_allocations'))
    )
    op.create_index('ix_allocations_batch_id', 'allocations', ['batch_id'], unique=False)
    op.create_index('ix_allocations_dealer_id_status', 'allocations', ['dealer_id', 'status'], unique=False)
    op.create_index('ix_allocations_serial', 'allocations', ['serial'], unique=False)
    op.create_table('dealer_redemptions',
    sa.Column('dealer_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_staff_id', sa.UUID(), nullable=True),
    sa.Column('reward_id', sa.UUID(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('reward_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('processed_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('pending','approved','rejected','fulfilled','cancelled')", name=op.f('ck_dealer_redemptions_status_valid')),
    sa.CheckConstraint('points > 0', name=op.f('ck_dealer_redemptions_points_positive')),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], name=op.f('fk_dealer_redemptions_dealer_id_dealers')),
    sa.ForeignKeyConstraint(['processed_by_admin_id'], ['admins.id'], name=op.f('fk_dealer_redemptions_processed_by_admin_id_admins')),
    sa.ForeignKeyConstraint(['requested_by_staff_id'], ['dealer_staff.id'], name=op.f('fk_dealer_redemptions_requested_by_staff_id_dealer_staff')),
    sa.ForeignKeyConstraint(['reward_id'], ['dealer_rewards.id'], name=op.f('fk_dealer_redemptions_reward_id_dealer_rewards')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dealer_redemptions'))
    )
    op.create_index('ix_dealer_redemptions_dealer_id_created_at', 'dealer_redemptions', ['dealer_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_dealer_redemptions_status', 'dealer_redemptions', ['status'], unique=False)
    op.create_table('warranties',
    sa.Column('serial', sa.String(length=128), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('model_name', sa.String(length=200), nullable=True),
    sa.Column('model_code', sa.String(length=64), nullable=True),
    sa.Column('warranty_months', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.UUID(), nullable=True),
    sa.Column('staff_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('invoice_ref', sa.String(length=120), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('warranty_start_date', sa.Date(), nullable=False),
    sa.Column('warranty_end_date', sa.Date(), nullable=False),
    sa.Column('backdate_days', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('backdate_approved_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('source', sa.String(length=20), server_default=sa.text("'dealer'"), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('proof_file_key', sa.String(length=400), nullable=True),
    sa.Column('unit_unverified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source in ('dealer','customer_self','admin','migration')", name=op.f('ck_warranties_source_valid')),
    sa.CheckConstraint("status in ('pending_confirmation','pending_review','pending_backdate','active','claimed','voided')", name=op.f('ck_warranties_status_valid')),
    sa.CheckConstraint('backdate_days >= 0', name=op.f('ck_warranties_backdate_days_non_negative')),
    sa.CheckConstraint('warranty_end_date >= warranty_start_date', name=op.f('ck_warranties_dates_ordered')),
    sa.CheckConstraint('warranty_months > 0', name=op.f('ck_warranties_warranty_months_positive')),
    sa.ForeignKeyConstraint(['backdate_approved_by_admin_id'], ['admins.id'], name=op.f('fk_warranties_backdate_approved_by_admin_id_admins')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_warranties_customer_id_customers')),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], name=op.f('fk_warranties_dealer_id_dealers')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_warranties_product_id_products')),
    sa.ForeignKeyConstraint(['staff_id'], ['dealer_staff.id'], name=op.f('fk_warranties_staff_id_dealer_staff')),
    sa.ForeignKeyConstraint(['unit_id'], ['product_units.id'], name=op.f('fk_warranties_unit_id_product_units')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warranties'))
    )
    op.create_index('ix_warranties_customer_id', 'warranties', ['customer_id'], unique=False)
    op.create_index('ix_warranties_dealer_id_created_at', 'warranties', ['dealer_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_warranties_serial', 'warranties', ['serial'], unique=False)
    op.create_index('ix_warranties_status', 'warranties', ['status'], unique=False)
    op.create_index('ix_warranties_warranty_end_date', 'warranties', ['warranty_end_date'], unique=False)
    op.create_table('claims',
    sa.Column('reference', sa.String(length=16), nullable=False),
    sa.Column('warranty_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('issue_type', sa.String(length=60), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'open'"), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('handled_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('open','in_review','approved','rejected','closed')", name=op.f('ck_claims_status_valid')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_claims_customer_id_customers')),
    sa.ForeignKeyConstraint(['handled_by_admin_id'], ['admins.id'], name=op.f('fk_claims_handled_by_admin_id_admins')),
    sa.ForeignKeyConstraint(['warranty_id'], ['warranties.id'], name=op.f('fk_claims_warranty_id_warranties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims')),
    sa.UniqueConstraint('reference', name=op.f('uq_claims_reference'))
    )
    op.create_index('ix_claims_status_created_at', 'claims', ['status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_claims_warranty_id', 'claims', ['warranty_id'], unique=False)
    op.create_table('dealer_ledger_entries',
    sa.Column('dealer_id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('warranty_id', sa.UUID(), nullable=True),
    sa.Column('redemption_id', sa.UUID(), nullable=True),
    sa.Column('rate_version_id', sa.UUID(), nullable=True),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], name=op.f('fk_dealer_ledger_entries_admin_id_admins')),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], name=op.f('fk_dealer_ledger_entries_dealer_id_dealers')),
    sa.ForeignKeyConstraint(['rate_version_id'], ['dealer_point_rates.id'], name=op.f('fk_dealer_ledger_entries_rate_version_id_dealer_point_rates')),
    sa.ForeignKeyConstraint(['redemption_id'], ['dealer_redemptions.id'], name=op.f('fk_dealer_ledger_entries_redemption_id_dealer_redemptions')),
    sa.ForeignKeyConstraint(['staff_id'], ['dealer_staff.id'], name=op.f('fk_dealer_ledger_entries_staff_id_dealer_staff')),
    sa.ForeignKeyConstraint(['warranty_id'], ['warranties.id'], name=op.f('fk_dealer_ledger_entries_warranty_id_warranties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dealer_ledger_entries'))
    )
    op.create_index('ix_dealer_ledger_entries_dealer_id_created_at', 'dealer_ledger_entries', ['dealer_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_dealer_ledger_entries_type', 'dealer_ledger_entries', ['type'], unique=False)
    op.create_index('ix_dealer_ledger_entries_warranty_id', 'dealer_ledger_entries', ['warranty_id'], unique=False)
    op.create_table('sms_messages',
    sa.Column('to_phone', sa.String(length=20), nullable=False),
    sa.Column('template_key', sa.String(length=60), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_template_id', sa.String(length=60), nullable=True),
    sa.Column('provider_message_id', sa.String(length=120), nullable=True),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('warranty_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('queued','sent','failed','delivered','undelivered')", name=op.f('ck_sms_messages_status_valid')),
    sa.ForeignKeyConstraint(['warranty_id'], ['warranties.id'], name=op.f('fk_sms_messages_warranty_id_warranties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sms_messages'))
    )
    op.create_index('ix_sms_messages_status_created_at', 'sms_messages', ['status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_sms_messages_to_phone', 'sms_messages', ['to_phone'], unique=False)
    op.create_index('ix_sms_messages_warranty_id', 'sms_messages', ['warranty_id'], unique=False)
    op.create_table('warranty_events',
    sa.Column('warranty_id', sa.UUID(), nullable=False),
    sa.Column('event', sa.String(length=40), nullable=False),
    sa.Column('from_status', sa.String(length=24), nullable=True),
    sa.Column('to_status', sa.String(length=24), nullable=True),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['warranty_id'], ['warranties.id'], name=op.f('fk_warranty_events_warranty_id_warranties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warranty_events'))
    )
    op.create_index('ix_warranty_events_warranty_id_created_at', 'warranty_events', ['warranty_id', sa.literal_column('created_at DESC')], unique=False)
    op.add_column('audit_logs', sa.Column('actor_type', sa.String(), server_default=sa.text("'admin'"), nullable=False))
    op.add_column('audit_logs', sa.Column('actor_id', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('actor_label', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('reason', sa.Text(), nullable=True))
    op.add_column('audit_logs', sa.Column('ip', sa.String(), nullable=True))
    op.add_column('products', sa.Column('warranty_months', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    # ---- Invariants Alembic cannot autogenerate ---------------------------
    # One warranty per physical unit. Partial, so voiding a warranty (a return)
    # frees the serial for a legitimate re-sale without deleting any history.
    op.execute(
        "CREATE UNIQUE INDEX uq_warranties_live_serial ON warranties (serial) "
        "WHERE status IN ('pending_confirmation','pending_review',"
        "'pending_backdate','active','claimed')"
    )
    # A serial is out with one dealer at a time; returned/revoked frees it.
    op.execute(
        "CREATE UNIQUE INDEX uq_allocations_open_serial ON allocations (serial) "
        "WHERE status IN ('allocated','registered')"
    )
    # A cause can be paid for, or reversed, exactly once — regardless of what
    # the service layer believes.
    op.execute(
        "CREATE UNIQUE INDEX uq_dealer_ledger_registration_credit "
        "ON dealer_ledger_entries (warranty_id) WHERE type = 'registration_credit'"
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_dealer_ledger_registration_reversal "
        "ON dealer_ledger_entries (warranty_id) WHERE type = 'registration_reversal'"
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_dealer_ledger_redemption_debit "
        "ON dealer_ledger_entries (redemption_id) WHERE type = 'redemption_debit'"
    )
    # Exactly one rate in force per product.
    op.execute(
        "CREATE UNIQUE INDEX uq_dealer_point_rates_current "
        "ON dealer_point_rates (product_id) WHERE effective_to IS NULL"
    )

    # Append-only is a trigger, not a comment, so a careless migration or an
    # admin at a psql prompt cannot rewrite point history either.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION reject_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION '% is append-only; % is not permitted (row id %)',
                TG_TABLE_NAME, TG_OP, OLD.id
                USING ERRCODE = 'restrict_violation';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for _table in ("dealer_ledger_entries", "warranty_events"):
        op.execute(
            f"CREATE TRIGGER {_table}_append_only "
            f"BEFORE UPDATE OR DELETE ON {_table} "
            f"FOR EACH ROW EXECUTE FUNCTION reject_mutation()"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for _table in ("dealer_ledger_entries", "warranty_events"):
        op.execute(f"DROP TRIGGER IF EXISTS {_table}_append_only ON {_table}")
    op.execute("DROP FUNCTION IF EXISTS reject_mutation()")
    for _ix in (
        "uq_dealer_point_rates_current",
        "uq_dealer_ledger_redemption_debit",
        "uq_dealer_ledger_registration_reversal",
        "uq_dealer_ledger_registration_credit",
        "uq_allocations_open_serial",
        "uq_warranties_live_serial",
    ):
        op.execute(f"DROP INDEX IF EXISTS {_ix}")

    op.drop_column('products', 'warranty_months')
    op.drop_column('audit_logs', 'ip')
    op.drop_column('audit_logs', 'reason')
    op.drop_column('audit_logs', 'actor_label')
    op.drop_column('audit_logs', 'actor_id')
    op.drop_column('audit_logs', 'actor_type')
    op.drop_index('ix_warranty_events_warranty_id_created_at', table_name='warranty_events')
    op.drop_table('warranty_events')
    op.drop_index('ix_sms_messages_warranty_id', table_name='sms_messages')
    op.drop_index('ix_sms_messages_to_phone', table_name='sms_messages')
    op.drop_index('ix_sms_messages_status_created_at', table_name='sms_messages')
    op.drop_table('sms_messages')
    op.drop_index('ix_dealer_ledger_entries_warranty_id', table_name='dealer_ledger_entries')
    op.drop_index('ix_dealer_ledger_entries_type', table_name='dealer_ledger_entries')
    op.drop_index('ix_dealer_ledger_entries_dealer_id_created_at', table_name='dealer_ledger_entries')
    op.drop_table('dealer_ledger_entries')
    op.drop_index('ix_claims_warranty_id', table_name='claims')
    op.drop_index('ix_claims_status_created_at', table_name='claims')
    op.drop_table('claims')
    op.drop_index('ix_warranties_warranty_end_date', table_name='warranties')
    op.drop_index('ix_warranties_status', table_name='warranties')
    op.drop_index('ix_warranties_serial', table_name='warranties')
    op.drop_index('ix_warranties_dealer_id_created_at', table_name='warranties')
    op.drop_index('ix_warranties_customer_id', table_name='warranties')
    op.drop_table('warranties')
    op.drop_index('ix_dealer_redemptions_status', table_name='dealer_redemptions')
    op.drop_index('ix_dealer_redemptions_dealer_id_created_at', table_name='dealer_redemptions')
    op.drop_table('dealer_redemptions')
    op.drop_index('ix_allocations_serial', table_name='allocations')
    op.drop_index('ix_allocations_dealer_id_status', table_name='allocations')
    op.drop_index('ix_allocations_batch_id', table_name='allocations')
    op.drop_table('allocations')
    op.drop_index('ix_idempotency_keys_created_at', table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index('ix_dealer_staff_dealer_id', table_name='dealer_staff')
    op.drop_table('dealer_staff')
    op.drop_index('ix_dealer_point_rates_product_id', table_name='dealer_point_rates')
    op.drop_table('dealer_point_rates')
    op.drop_table('allocation_batches')
    op.drop_index('ix_dealers_status', table_name='dealers')
    op.drop_table('dealers')
    op.drop_table('dealer_rewards')
    op.drop_index('ix_customers_name', table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
