import { api } from './client';
import type { RegisterBody, RegisterOut, WarrantyOut } from './types';

/**
 * Create the sale record.
 *
 * The idempotency key is generated by the CALLER when the dealer taps submit and
 * reused on every retry forever — see offline/queue.ts. It is a parameter rather
 * than something generated here precisely so a retry cannot accidentally mint a
 * fresh key and pay twice.
 */
export async function createRegistration(
  body: RegisterBody,
  idempotencyKey: string
): Promise<RegisterOut> {
  const resp = await api.post<RegisterOut>('/dealer/registrations', body, {
    headers: { 'Idempotency-Key': idempotencyKey },
  });
  return resp.data;
}

export async function listRegistrations(limit = 50, offset = 0): Promise<WarrantyOut[]> {
  const resp = await api.get<WarrantyOut[]>('/dealer/registrations', {
    params: { limit, offset },
  });
  return resp.data;
}
